version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip
      - pip install -r cars-kmeans-mlops/requirements.txt
  build:
    commands:
      - python -m compileall cars-kmeans-mlops/src cars-kmeans-mlops/pipelines cars-kmeans-mlops/scripts
      - pytest -q cars-kmeans-mlops/tests
